#!/bin/bash

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "${source_dir}"

CHIBIOS_SRC="${source_dir}/ChibiOS"
LWIP_SRC="${CHIBIOS_SRC}/ext/lwip/"

unpack_lwip () {
  cd "${CHIBIOS_SRC}/ext/";
  7z x lwip-*.7z;
  if [ ! -d "${LWIP_SRC}" ]; then
    echo "Unpacking LWIP failed! Exiting..";
    exit 1;
  fi
  cd "${source_dir}";
}

# Unpack LwIP
if [ ! -d "${LWIP_SRC}" ]; then
  echo "LWIP Directory not found, unpacking..";
  unpack_lwip;
fi

# Patch LwIP bindings for using system time lib
patch -d ${CHIBIOS_SRC} -p 1 -N --dry-run --silent < lwip-use-system-time.patch > /dev/null;
if [ $? -eq 0 ];
then
  patch -d ${CHIBIOS_SRC} -p 1 -N < lwip-use-system-time.patch;
fi

make
