#!/bin/bash

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "${source_dir}"

CHIBIOS_SRC="${source_dir}/ChibiOS"
LWIP_SRC="${CHIBIOS_SRC}/ext/lwip/"
WOLFSSL_SRC="${CHIBIOS_SRC}/ext/wolfssl/"

unpack_lwip () {
  cd "${CHIBIOS_SRC}/ext/";
  7z x lwip-*.7z;
  if [ ! -d "${LWIP_SRC}" ]; then
    echo "Unpacking LWIP failed! Exiting..";
    exit 1;
  fi
  cd "${source_dir}";
}

unpack_wolfssl () {
  cd "${CHIBIOS_SRC}/ext/";
  7z x wolfssl-*.7z;
  if [ ! -d "${LWIP_SRC}" ]; then
    echo "Unpacking WolfSSL failed! Exiting..";
    exit 1;
  fi
  cd "${source_dir}";
}

# Unpack LwIP
if [ ! -d "${LWIP_SRC}" ]; then
  echo "LWIP Directory not found, unpacking..";
  unpack_lwip;
fi

# Unpack WolfSSL
#if [ ! -d "${WOLFSSL_SRC}" ]; then
#  echo "WolfSSL Directory not found, unpacking..";
#  unpack_wolfssl;
#fi

# Patch LwIP bindings for using system time lib
#patch -d ${CHIBIOS_SRC} -p 1 -N --dry-run --silent < lwip-use-system-time.patch > /dev/null;
#if [ $? -eq 0 ];
#then
#  patch -d ${CHIBIOS_SRC} -p 1 -N < lwip-use-system-time.patch;
#fi

make

size=`arm-none-eabi-size build/g5500-ethernet-controller.elf | sed -n 2p`

size_text=`echo $size | grep -o -E '[0-9]+' | sed -n 1p`
size_data=`echo $size | grep -o -E '[0-9]+' | sed -n 2p`
size_bss=`echo $size | grep -o -E '[0-9]+' | sed -n 3p`

size_flash=$(($size_text+$size_data))
size_ram=$(($size_data+$size_bss))

printf "RAM Usage: %5s B\n" ${size_ram}
printf "ROM Usage: %5s B\n" ${size_flash}