#!/usr/bin/env bash

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "$source_dir"

flashtool="arm-none-eabi-gdb"
programmer=false
binary="builds/g5500-ethernet-controller.elf"

locate_black_magic() {
  probe="`ls 2>/dev/null -Ub1 -- /dev/serial/by-id/usb-Black_Sphere_Technologies_Black_Magic_Probe_*-if00 | head -n 1`"
  if ! [ -z "$probe" ]
  then
    echo "$probe"
    return 0
  fi
  return 1
}
debug_target() {
	$flashtool -q \
    -ex 'file '$binary                          \
    -ex 'target extended-remote '$programmer    \
    -ex 'monitor tpwr $programmer_power'        \
    -ex 'monitor swdp_scan'                     \
    -ex 'attach 1'                              \
    -ex 'set mem inaccessible-by-default off'   \
    -ex 'load '$binary                          \
    -ex 'compare-sections'
}

if programmer="`locate_black_magic`";
then
	debug_target;
fi